version: '3'

services:
  vue:
    build:
      context: ./Profile_vue
    ports:
      - "8080:8080"
    volumes:
      - ./Profile_vue:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
